### ISSUE TITLE
test_constant fails with python3.11 and gvar-13.0.2

### ISSUE THREAD

**Issue by APN-Pucky** [gplepage/vegas#35] opened 2024-03-16 09:40 UTC
![2024-03-16_10-38-50_apn](https://github.com/gplepage/vegas/assets/4533248/462b1a2b-ce14-4bc7-82cc-4a153fc2eb1d)

Is that only a problem on my side?

**Comment by gplepage** [comment] 2024-03-16 17:44
This suggests there may be a problem. The ratio being tested equals 2.0 to machine precision more or less, not just 3 or 4 digits. If you modify method `test_constant` in `tests/test_vegas.py` as follows,
```python

    def test_constant(self):
        " integral of a constant "
        @batchintegrand
        def g(x):
            return np.ones(x.shape[0], float)
        # test weighted results
        integ = Integrator([(0,1)],analyzer=reporter(ngrid=30))
        print()
        integ(g, nitn=1, neval=1e2, neval_frac=0.5)
        res = integ(g, nitn=4, neval=1e2)
        print('xxxx ratio =', res.itn_results[0].sdev, '/', res.sdev, '=', res.itn_results[0].sdev / res.sdev, '\n')
        self.assertAlmostEqual(res.itn_results[0].sdev / res.sdev, 2.0)
        # test unweighted results
        res = integ(g, nitn=4, neval=1e2, adapt=False)
        self.assertAlmostEqual(res.itn_results[0].sdev / res.sdev, 2.0)
        # zero
        @batchintegrand
        def g(x):
            return np.zeros(x.shape[0], float)
        # test weighted results
        integ = Integrator([(0,1)],)
        res = integ(g, nitn=4, neval=1e2)
        self.assertEqual(res.mean, 0.0)
```
I would expect the following output:
```
...............
Integrator Settings:
    100 (approx) integrand evaluations in each of 1 iterations
    number of: strata/axis = [24]
               increments/axis = [24]
               h-cubes = 24  processors = 1
               evaluations/batch >= 5e+04
               2 <= evaluations/h-cube <= 5e+04
    minimize_mem = False  adapt_to_errors = False  adapt = True
    accuracy: relative = 0  absolute = 0
    damping: alpha = 0.5  beta= 0.75

    axis    integration limits
    --------------------------
       0            (0.0, 1.0)

    itn  1: 1.0000000000(48)
 all itn's: 1.0000000000(48)
    neval = 96  neval/h-cube = (2, 4)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


Integrator Settings:
    100 (approx) integrand evaluations in each of 4 iterations
    number of: strata/axis = [24]
               increments/axis = [24]
               h-cubes = 24  processors = 1
               evaluations/batch >= 5e+04
               2 <= evaluations/h-cube <= 5e+04
    minimize_mem = False  adapt_to_errors = False  adapt = True
    accuracy: relative = 0  absolute = 0
    damping: alpha = 0.5  beta= 0.75

    axis    integration limits
    --------------------------
       0            (0.0, 1.0)

    itn  1: 1.0000000000(68)
 all itn's: 1.0000000000(68)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  2: 1.0000000000(68)
 all itn's: 1.0000000000(48)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  3: 1.0000000000(68)
 all itn's: 1.0000000000(39)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  4: 1.0000000000(68)
 all itn's: 1.0000000000(34)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


xxxx ratio = 6.801418432409144e-09 / 3.400709216204572e-09 = 2.0 

Integrator Settings:
    100 (approx) integrand evaluations in each of 4 iterations
    number of: strata/axis = [24]
               increments/axis = [24]
               h-cubes = 24  processors = 1
               evaluations/batch >= 5e+04
               2 <= evaluations/h-cube <= 5e+04
    minimize_mem = False  adapt_to_errors = False  adapt = False
    accuracy: relative = 0  absolute = 0
    damping: alpha = 0  beta= 0

    axis    integration limits
    --------------------------
       0            (0.0, 1.0)

    itn  1: 1.0000000000(68)
 all itn's: 1.0000000000(68)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  2: 1.0000000000(68)
 all itn's: 1.0000000000(48)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  3: 1.0000000000(68)
 all itn's: 1.0000000000(39)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


    itn  4: 1.0000000000(68)
 all itn's: 1.0000000000(34)
    neval = 48  neval/h-cube = (2, 2)
    chi2/dof = 0.00  Q = 1.00  time = 0.00
    grid[ 0] = [0.    0.042 0.083 0.125 0.167 0.208 0.25  0.292 0.333
                0.375 0.417 0.458 0.5   0.542 0.583 0.625 0.667 0.708
                0.75  0.792 0.833 0.875 0.917 0.958 1.   ]


...........................................
```
I would be curious to see what you get on your machine.  

This test is very artificial. It is quite possible that `vegas` works properly elsewhere but fails this test.

**Comment by APN-Pucky** [comment] 2024-03-16 17:47
I ran it on some CI/docker too an there I had no problem. So it seems to be machine/other software specific. I'll try what you suggested when I get time for it.

**Comment by APN-Pucky** [comment] 2024-03-16 17:52
Sooner than I expected :)
[python3.12.log](https://github.com/gplepage/vegas/files/14624733/python3.12.log)
[python3.11.log](https://github.com/gplepage/vegas/files/14624734/python3.11.log)

**Comment by APN-Pucky** [comment] 2024-03-16 17:58
Maybe I have too recent scipy/numpy installations:
- scipy-1.12.0
- numpy-1.26.4
- (cython-3.0.8)

**Comment by gplepage** [comment] 2024-03-17 01:55
You should probably not waste more time on this. I think the problem is with the test not with `vegas`. I will sort it out but in the meantime I think that `vegas` is almost certainly working on your system.

I will post here again once I have understood why there is a difference between what you get and what I get for that test.

**Comment by gplepage** [comment] 2024-03-18 01:02
I think the differences are due to differences in roundoff errors. These would not be an issue normally but this particular test is unusually sensitive to such errors. `vegas` normally protects against roundoff error but this example revealed a place where that wasn't done. A fix will be in place for the next release. I will also be dropping this test because it is too idiosyncratic. In any case, your installation of `vegas` is probably fine if this is the only test that fails.

Thanks for pointing out the issue here (and also in `gvar`).

**Closed** 2024-03-18 18:51 UTC
