### ISSUE TITLE
NumPy issues with batch mode

### ISSUE THREAD

**Issue by irina-ru** [gplepage/vegas#39] opened 2024-12-16 05:22 UTC
Hi there,

First of all, thank you for providing VEGAS for Python and the extensive documentation, it has been very helpful!

I have a costly integral that I'd like to compute faster using batch mode. Part of the integrand is the parametrization of the four-particle phase space, for which I need NumPy vectors and matrices. However, when defining four-momenta as ```ndarray``` objects, such as for example 
```python
tau0 = #some_constant
s = #some_other_constant

@vegas.rbatchintegrand
def integrand(x):
    x1 = (1 - tau0) * x[0] + tau0
    x2 = (1 - tau0 / x1) * x[1] + tau0 / x1
    sh = x1 *x2 * s
    ...
    k1 = np.array([np.sqrt(sh) / 2, 0, 0, np.sqrt(sh) / 2])
    ...
    return #function_expression

integral = vegas.Integrator(9 * [[0, 1]])
warmup = integral(integrand, nitn=5, neval=100000)
result = integral(integrand, nitn=5, neval=1000000)
print('result = %s, Q = %.2f' % (result, result.Q))
```
I obtain the following error:
```
    k1 = np.array([np.sqrt(sh) / 2, 0, 0, np.sqrt(sh) / 2])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```
Such is the case with any NumPy objects such as arrays or matrices; the dimensions seem to not work in batch mode. In the documentation, it says that arrays of type ```x[d]``` will be implicitly understood to represent ```x[d, :]``` when using the ```@vegas.rbatchintegrand``` decorator. However, this doesn't seem to work automatically for NumPy arrays.

Is there a way to use NumPy and still evaluate the integral in batch mode?

NumPy version ```2.2.0```, VEGAS version ```6.2```

**Comment by gplepage** [comment] 2024-12-16 14:35
In the `k1` statement, Numpy wants every element of the 4-element list to have the same shape, but `np.sqrt(sh) / 2` is a 1-d array with something like 50,000 elements while `0` is a scalar (with only 1 element). One way to fix this is to replace the `k1` statement by:
```
    k1 = np.zeros((4, len(x1)), float)
    k1[0] = k1[-1] = np.sqrt(sh) / 2
```
The second index on `k1` is the batch index. 

`sh` is a 1-d array because `x[0]` and `x[1]` are arrays when in batch mode. Usually small changes like this are needed when converting an integrand to batch mode. 

Another way to fix it would be to define `zero = np.zeros(len(sh), float)` and set 
```
k1 = np.array([np.sqrt(sh) / 2, zero, zero, np.sqrt(sh) / 2])
```

**Comment by gplepage** [comment] 2024-12-28 22:50
I am closing this because I believe the problem is solved. Feel free to reopen it if I am wrong.

**Closed by gplepage** 2024-12-28 22:50 UTC
