### ISSUE TITLE
Integral depends on the distributions

### ISSUE THREAD

**Issue by Gaussian-art** [gplepage/vegas#32] opened 2023-05-10 13:40 UTC
I am using vegas to calculate an integral together with some distributions. I followed the ideas described in the [documentation](https://vegas.readthedocs.io/en/latest/tutorial.html#calculating-distributions), but the result I get when doing the integral alone and the result when doing the integral with distributions is slightly lower. This is not a big deal for one distribution, but I am computing several distributions together so, in the end, I am integrating a vector of ~100 components and this effect becomes relevant: the result is ~93% of the original (the error of the integrals is ~0.5%)

I know that the integral should adapt only to the total value (which is the first component), but it seems that the final result depends on the distributions, is there a way to prevent this? If it is not possible, is there an easy way to extract the relevant information (the points where the integral was evaluated and the corresponding weights) to reconstruct the distributions after the integral was computed?

Thank you

**Comment by gplepage** [comment] 2023-05-11 18:10
I was able to get similar behavior from a simple test code with 200 components. It went away when I increased the number of evaluations per iteration (``neval``) by a factor of ten. Have you tried increasing ``neval``?

The problem is with the weighted averages of the results from several iterations. Calculating the weights involves the inversion of a fairly singular covariance matrix, which makes the results more sensitive to fluctuations. This sensitivity gets worse as the number of components is increased, which means you need a larger ``neval`` (to reduce the fluctuations).

Another alternative, which is probably faster and better, is to do your integral in two steps. In the first you adapt the ``vegas`` integrator to the function, discarding the results. In the second step, you turn off adaptation (since the integrator is already adapted, from the first step). Then ``vegas`` will use unweighted averages to combine results from different iterations. Here is sample code for an integrand with 100 components::

    itg = vegas.Integrator(100 * [[0,1]])
    itg(f, neval=10_000)                               # discard results from first step
    r = itg(f, neval=10_000, adapt=False)  # final result, with no further adaptation

The problem you are having cannot happen when you do things this way.  (See the discussion in the documentation about ``adapt=False``.

I will add a discussion to the documentation about this problem in the next release.

If you want access to the weights and integration points, you can use code from the 
documentation section on "vegas as a Random Number Generator" to do your integrals. You then can collect the weights and points. However, I would recommend trying the ``adapt=False`` approach -- it is far more robust.

**Comment by gplepage** [comment] 2023-05-13 15:55
The issue you are encountering is now discussed in the tutorial on Calculating Distributions, in ``vegas`` version 5.4.1. See: 

https://vegas.readthedocs.io/en/latest/tutorial.html#calculating-distributions

**Comment by gplepage** [comment] 2023-07-23 17:25
I am closing this issue because it is addressed by the new documentation discussed above.

**Closed by gplepage** 2023-07-23 17:25 UTC
